// Checks only synthetic content against the explicitly supplied cloud URL.
import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
try { process.loadEnvFile(); } catch { /* environment may be injected */ }
const url = process.argv[2];
if (!url || !process.env.APP_PASSWORD) throw new Error('Provide cloud URL and private APP_PASSWORD.');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
page.setDefaultTimeout(30000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const title = 'Prueba temporal ' + Date.now();
try {
 await page.goto(url);
 await page.getByLabel('Nuestra contraseña').fill(process.env.APP_PASSWORD);
 await page.getByRole('button',{name:'Entrar a nuestro rincón'}).click();
 await page.getByRole('heading',{name:/Nuestros momentos/}).waitFor();
 await page.getByRole('button',{name:'Palabras',exact:true}).click();
 await page.getByRole('button',{name:'Escribir',exact:true}).click();
 await page.getByLabel('Título',{exact:true}).fill(title);
 await page.getByLabel('Tu carta',{exact:true}).fill('Contenido sintético de verificación.\nSe elimina al terminar.');
 await page.getByLabel('De parte de').fill('Prueba');
 await page.getByRole('button',{name:'Guardar estas palabras'}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.reload();
 await page.getByRole('heading',{name:/Nuestros momentos/}).waitFor();
 await page.getByRole('button',{name:'Palabras',exact:true}).click();
 await page.getByRole('heading',{name:title,exact:true}).waitFor();
 console.log('Firebase: login, create letter, reload and persisted session/content PASS');
 await page.getByRole('button',{name:'Eliminar '+title,exact:true}).click();
 await page.getByRole('button',{name:'Eliminar',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Recuerdos',exact:true}).click();
 await page.getByRole('button',{name:'Subir recuerdos',exact:true}).click();
 await page.getByLabel('Fotos y videos',{exact:true}).setInputFiles({name:'cielo.png',mimeType:'image/png',buffer:readFileSync('tests/fixtures/cielo.png')});
 await page.getByLabel('Título',{exact:true}).fill(title);
 await page.getByRole('button',{name:'Guardar en nuestro rincón'}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Abrir '+title,exact:true}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Abrir '+title,exact:true}).waitFor();
 const card = page.getByRole('button',{name:'Abrir '+title,exact:true});
 const src = await card.locator('img').getAttribute('src');
 const result = await page.evaluate(async path => {
  const r = await fetch(path.replace('?thumb=1',''),{headers:{Range:'bytes=0-9'}});
  return {status:r.status,range:r.headers.get('Content-Range'),cache:r.headers.get('Cache-Control'),size:(await r.arrayBuffer()).byteLength};
 },src);
 if (result.status!==206 || result.size!==10 || result.cache!=='no-store') throw new Error('Private Range proxy failed: '+JSON.stringify(result));
 console.log('Supabase: upload original/thumbnail, reload, authenticated Range=206 PASS');
 await page.screenshot({path:'test-results/cloud-real-mobile.png',fullPage:true});
 // Check logout denies a fresh file request, then log back in to remove only our synthetic photo.
 await page.getByRole('button',{name:'Cerrar sesión'}).click();
 await page.getByLabel('Nuestra contraseña').waitFor();
 const denied = await page.evaluate(async path => (await fetch(path)).status,src);
 if (denied!==401) throw new Error('File accessible after logout: '+denied);
 console.log('Private files after logout: 401 PASS');
 await page.getByLabel('Nuestra contraseña').fill(process.env.APP_PASSWORD);
 await page.getByRole('button',{name:'Entrar a nuestro rincón'}).click();
 await page.getByRole('button',{name:'Abrir '+title,exact:true}).click();
 await page.getByRole('button',{name:'Eliminar recuerdo'}).click();
 await page.getByRole('button',{name:'Eliminar',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 // Exercise streamed audio against the real private bucket.
 await page.getByRole('button',{name:'Música',exact:true}).click();
 await page.getByRole('button',{name:'Subir canción',exact:true}).click();
 const samples = 44100 * 2, wav = Buffer.alloc(44 + samples * 2);
 wav.write('RIFF'); wav.writeUInt32LE(36 + samples * 2,4); wav.write('WAVE',8);
 wav.write('fmt ',12); wav.writeUInt32LE(16,16); wav.writeUInt16LE(1,20); wav.writeUInt16LE(1,22);
 wav.writeUInt32LE(44100,24); wav.writeUInt32LE(88200,28); wav.writeUInt16LE(2,32); wav.writeUInt16LE(16,34);
 wav.write('data',36); wav.writeUInt32LE(samples * 2,40);
 for(let i=0;i<samples;i++) wav.writeInt16LE(Math.round(Math.sin(i / 44100 * 2 * Math.PI * 220) * 500),44+i*2);
 await page.getByLabel('Archivos de música').setInputFiles({name:'prueba.wav',mimeType:'audio/wav',buffer:wav});
 await page.getByLabel('Título',{exact:true}).fill(title+' audio');
 await page.getByRole('button',{name:'Guardar en nuestro rincón'}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Reproducir '+title+' audio',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('audio')?.currentTime > 0);
 await page.getByRole('button',{name:'Pausar música'}).click();
 await page.getByRole('button',{name:'Eliminar canción '+title+' audio',exact:true}).click();
 await page.getByRole('button',{name:'Eliminar',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 console.log('Private audio upload/playback and deletion: PASS');
 await page.getByRole('button',{name:'Recuerdos',exact:true}).click();
 const recording = await page.evaluate(async () => {
  const canvas=document.createElement('canvas'); canvas.width=320;canvas.height=240;
  const context=canvas.getContext('2d'); const stream=canvas.captureStream(10);
  const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),chunks=[];
  const done=new Promise(resolve=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>resolve(new Blob(chunks,{type:'video/webm'}));});
  recorder.start();let frame=0;
  const timer=setInterval(()=>{context.fillStyle=frame++%2?'#edbfd1':'#dceef9';context.fillRect(0,0,320,240);},100);
  await new Promise(resolve=>setTimeout(resolve,1800));clearInterval(timer);recorder.stop();
  const blob=await done;stream.getTracks().forEach(track=>track.stop());return Array.from(new Uint8Array(await blob.arrayBuffer()));
 });
 await page.getByRole('button',{name:'Subir recuerdos',exact:true}).click();
 await page.getByLabel('Fotos y videos',{exact:true}).setInputFiles({name:'prueba.webm',mimeType:'video/webm',buffer:Buffer.from(recording)});
 await page.getByLabel('Título',{exact:true}).fill(title+' video');
 await page.getByRole('button',{name:'Guardar en nuestro rincón'}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Abrir '+title+' video',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('dialog video')?.readyState>0);
 if(!await page.locator('dialog video').evaluate(v=>v.paused))throw new Error('Video unexpectedly autoplayed');
 await page.locator('dialog video').evaluate(v=>v.play());
 await page.waitForFunction(()=>document.querySelector('dialog video')?.currentTime>0);
 await page.getByRole('button',{name:'Eliminar recuerdo'}).click();
 await page.getByRole('button',{name:'Eliminar',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 console.log('Private video upload, paused opening, playback and deletion: PASS');
 await page.getByRole('button',{name:'Cerrar sesión'}).click();
 if (errors.length) throw new Error('Browser errors: '+JSON.stringify(errors));
 console.log('Synthetic photo/letter removed; browser flow PASS');
} catch (error) {
 await page.screenshot({path:'test-results/cloud-smoke-failure.png',fullPage:true});
 console.error((await page.locator('body').innerText()).slice(-2000));
 throw error;
} finally { await browser.close(); }
